# ------------------------------------------------------------------------------
#  (c) Crown copyright Met Office. All rights reserved.
#  The file LICENCE, distributed with this code, contains details of the terms
#  under which the code may be used.
# ------------------------------------------------------------------------------

name: Fortran lint
on:
  workflow_call:

    inputs:
      runner:
        description: 'The runner to use for the job'
        required: false
        default: 'ubuntu-latest'
      timeout:
        description: 'The maximum time in minutes the job can run for'
        required: false
        default: 10
      python-version:
        description: 'The Python version to use'
        required: false
        default: '3.14'

jobs:
  fortitude-linting:
    name: Fortran lint
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.python-version }}

      - name: Cache uv packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ inputs.python-version }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: minimize uv cache
        run: uv cache clean && uv cache prune || true

      - name: Install Fortitude Linter
        run: |
          uv self update -q
          uv install fortitude-lint==0.7.3

      - name: Run Fortitude Linter
        run: |
          output=$(fortitude check)
          if [[ -n "$output" ]]; then
            echo "$output"
            echo "ERROR: Fortran styling issues found."
            echo -e "\n Please run 'fortitude check --fix' to fix these"
            echo "issues automatically where possible."
            exit 1
          else
            echo "No Fortran styling issues found :) ."
          fi
        timeout-minutes: ${{ inputs.timeout }}
